"""empty message

Revision ID: 4c4068f8c268
Revises: 71c544e2c0c7
Create Date: 2019-12-05 16:58:18.486899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4068f8c268'
down_revision = '71c544e2c0c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temfolder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('temfile', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temfile', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('temfolder')
    # ### end Alembic commands ###
