"""empty message

Revision ID: 5ef4b0e24ebf
Revises: dfb6c94161dd
Create Date: 2019-11-16 15:13:53.566204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef4b0e24ebf'
down_revision = 'dfb6c94161dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'activemembers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('activemembers', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
