"""empty message

Revision ID: 71c544e2c0c7
Revises: 917cd467fc6e
Create Date: 2019-12-03 22:20:56.180577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c544e2c0c7'
down_revision = '917cd467fc6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temfile', sa.Column('changed', sa.Boolean(), nullable=True))
    op.add_column('temfile', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('temfile', sa.Column('loaded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temfile', 'loaded')
    op.drop_column('temfile', 'deleted')
    op.drop_column('temfile', 'changed')
    # ### end Alembic commands ###
