"""empty message

Revision ID: 90a1a7759249
Revises: a2ab268d1d19
Create Date: 2019-11-02 14:50:29.547909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90a1a7759249'
down_revision = 'a2ab268d1d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('write_access_users', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'write_access_users')
    # ### end Alembic commands ###
