"""empty message

Revision ID: 917cd467fc6e
Revises: 5ef4b0e24ebf
Create Date: 2019-11-16 15:14:16.515376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '917cd467fc6e'
down_revision = '5ef4b0e24ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('activemembers', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'activemembers')
    # ### end Alembic commands ###
