"""empty message

Revision ID: 9ba94e8929c8
Revises: 693ea516f056
Create Date: 2019-09-21 22:27:43.394106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ba94e8929c8'
down_revision = '693ea516f056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temfile')
    op.drop_table('project')
    op.drop_table('session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('session_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('repo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sha', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activemembers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='session_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='session_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('project_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('repo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='project_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('temfile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sha', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name='temfile_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='temfile_pkey')
    )
    # ### end Alembic commands ###
