"""Database initialization

Revision ID: a2ab268d1d19
Revises: 
Create Date: 2019-10-29 15:15:12.901603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ab268d1d19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temfile')
    op.drop_table('session')
    op.drop_table('project')

    
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('repo', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('repo', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('sha', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('activemembers', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('temfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('sha', sa.String(), nullable=True),
    sa.Column('delta1_start', sa.Integer(), nullable=True),
    sa.Column('delta1_amt', sa.Integer(), nullable=True),
    sa.Column('delta1_data', sa.String(), nullable=True),
    sa.Column('delta2_start', sa.Integer(), nullable=True),
    sa.Column('delta2_amt', sa.Integer(), nullable=True),
    sa.Column('delta2_data', sa.String(), nullable=True),
    sa.Column('delta3_start', sa.Integer(), nullable=True),
    sa.Column('delta3_amt', sa.Integer(), nullable=True),
    sa.Column('delta3_data', sa.String(), nullable=True),
    sa.Column('delta4_start', sa.Integer(), nullable=True),
    sa.Column('delta4_amt', sa.Integer(), nullable=True),
    sa.Column('delta4_data', sa.String(), nullable=True),
    sa.Column('hash1', sa.String(), nullable=True),
    sa.Column('hash2', sa.String(), nullable=True),
    sa.Column('hash3', sa.String(), nullable=True),
    sa.Column('hash4', sa.String(), nullable=True),
    sa.Column('hash5', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temfile')
    op.drop_table('session')
    op.drop_table('project')
    # ### end Alembic commands ###
