"""active members now an array

Revision ID: dfb6c94161dd
Revises: 90a1a7759249
Create Date: 2019-11-15 12:52:48.621825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb6c94161dd'
down_revision = '90a1a7759249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
